[functions.chat-ai]
enabled = true
verify_jwt = false
import_map = "./functions/chat-ai/deno.json"
entrypoint = "./functions/chat-ai/index.js"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/chat-ai/index.js"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-ai/*.html" ]